### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by bmaupin** [cypress-io/snapshot#172]
Is this project still maintained? Of course it hasn't had any updates in a while, but it seems very promising, especially given that screenshot snapshot testing isn't always reliable (I was never able to get it to create consistent screenshots due to https://github.com/cypress-io/cypress/issues/2681).

Unfortunately this plugin needs some love before it's usable. I ran into #18 and #116 in particular as blockers preventing me from using this plugin.

I'm not sure if they're something I could fix myself, but I'd want to know that PRs are still being accepted before spending any time looking into it.

If not, maybe it should be given some kind of deprecation notice, especially since it's under the @cypress-io organisation.

Thanks!

@tgriesser @brian-mann @jennifer-shehane

**Comment by bmaupin** [comment]
I found a maintained fork of this plugin that seems to probably be the best option right now: 

> Unlike `@cypress/snapshot`, this saves snapshots in their own files with a sensible default and strives to have ongoing Support for future Cypress Versions

https://github.com/datashard/snapshot

**Comment by jennifer-shehane** [comment]
@bmaupin No our team is not actively maintained this repo as we are focused on other priorities like the Cypress App itself and our other more popular plugins. We will archive this repo in order to more clearly communicate this.

I'm glad to see you found an alternative that is more actively maintained. Anyone is welcome to fork this repo in the future and create a snapshot library that they find useful.
